### ISSUE TITLE
Deprecated errors on install

### ISSUE THREAD

**Issue by bradydowling** [ide/dash-button#128]
I'm seeing errors on install and scan that look like node version issues but I've tried this with Node 6, Node 8, and Node 10, all with no success.

I installed Node via `nvm` which actually doesn't allow you to run `sudo npm run scan`. It initially gives an error saying `sudo: npm: command not found` and then I have to create a symlink for it to work.

This can't be caused by `nvm` can it? I'd prefer not to blow away `nvm` and install via `apt-get`.

### Version details

Node version: v8.15.0
npm version: 6.4.1
nvm version: 0.34.0
OS: Linux raspberrypi 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

### Error messages

```
$ npm install --save dash-button

> socketwatcher@0.3.0 install /home/pi/dash-listener/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/home/pi/dash-listener/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:
../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../socket_watcher.cpp:104:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
In file included from /home/pi/.node-gyp/8.15.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/8.15.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/pi/.node-gyp/8.15.0/include/node/v8.h:3901:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/pi/.node-gyp/8.15.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/home/pi/dash-listener/node_modules/socketwatcher/build'

> pcap@git+https://github.com/mranney/node_pcap.git#b4eb828fbfb3ad9a253351aa38cb41c203589712 install /home/pi/dash-listener/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/home/pi/dash-listener/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
  CXX(target) Release/obj.target/pcap_binding/pcap_session.o
../pcap_session.cc: In static member function ‘static void PcapSession::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../pcap_session.cc:46:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
In file included from /home/pi/.node-gyp/8.15.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/8.15.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../pcap_session.h:4,
                 from ../pcap_session.cc:7:
/home/pi/.node-gyp/8.15.0/include/node/v8.h:3901:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/pi/.node-gyp/8.15.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../pcap_session.cc: In static member function ‘static void PcapSession::PacketReady(u_char*, const pcap_pkthdr*, const u_char*)’:
../pcap_session.cc:85:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
 Nan::GetCurrentContext()->Global(), Nan::New(session->packet_ready_cb), 0, NULL);
                                                                                ^
In file included from ../pcap_session.h:4:0,
                 from ../pcap_session.cc:7:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
  COPY Release/pcap_binding.node
make: Leaving directory '/home/pi/dash-listener/node_modules/pcap/build'
npm WARN dash-listener@0.0.1 No description
npm WARN dash-listener@0.0.1 No repository field.

+ dash-button@3.2.0
added 57 packages from 24 contributors and audited 66 packages in 147.145s
found 0 vulnerabilities
```

Running `scan` seems to give similar node version type of errors.
```
$ sudo npm run scan
/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by bradydowling** [comment]
Looks like it's related to [this issue in pcap](https://github.com/node-pcap/node_pcap/pull/243) that was resolved in a later version. I'll have to try updating the `package.json` and then running `npm install` with the updated `pcap` to see if that addresses the issue. If that works then I'll make a PR.
